import type { PricingGroup } from "@/types";

/**
 * Prices are "from" figures for a compact hatchback. Larger vehicles scale by
 * the multipliers listed in `sizeTiers` and are confirmed after inspection.
 */
export const sizeTiers = [
  { label: "S — Compact", example: "Golf, Mini, A3", multiplier: "base" },
  { label: "M — Saloon / Estate", example: "3 Series, A6, Passat", multiplier: "+15%" },
  { label: "L — SUV / Coupé GT", example: "Q7, X5, Panamera", multiplier: "+30%" },
  { label: "XL — Large SUV / Van", example: "G-Class, Cullinan, V-Class", multiplier: "+45%" },
];

export const pricingGroups: PricingGroup[] = [
  {
    id: "exterior",
    title: "Exterior",
    description:
      "Maintenance and presentation work. The right cadence between larger protection jobs.",
    options: [
      {
        name: "Maintenance Wash",
        description: "The correct way to wash a coated or filmed car without adding swirls.",
        price: 90,
        duration: "2 – 3 h",
        serviceSlug: "exterior-detailing",
        includes: [
          "Snow foam pre-wash and pressure rinse",
          "Two-bucket contact wash",
          "Wheel faces and arches",
          "Forced-air dry and glass",
        ],
      },
      {
        name: "Exterior Detail",
        description: "Full decontamination with a six-month sealant.",
        price: 180,
        duration: "4 – 6 h",
        featured: true,
        serviceSlug: "exterior-detailing",
        includes: [
          "Everything in Maintenance Wash",
          "Iron fallout and tar removal",
          "Mechanical clay decontamination",
          "Barrels, calipers and trim",
          "Six-month paint sealant",
        ],
      },
      {
        name: "Full Detail",
        description: "Exterior and interior programmes plus an enhancement polish.",
        price: 540,
        duration: "1 – 2 days",
        serviceSlug: "full-detailing",
        includes: [
          "Complete exterior programme",
          "Complete interior programme",
          "Single-stage enhancement polish",
          "Engine bay and shuts",
          "12-month protection",
        ],
      },
    ],
  },
  {
    id: "interior",
    title: "Interior",
    description: "Cabin restoration, sanitising and long-term surface protection.",
    options: [
      {
        name: "Interior Refresh",
        description: "A thorough reset for a well-kept cabin.",
        price: 140,
        duration: "3 – 4 h",
        serviceSlug: "interior-detailing",
        includes: [
          "Full vacuum and compressed air",
          "Hard surfaces cleaned and matte-finished",
          "Glass inside",
          "Mats cleaned and dried",
        ],
      },
      {
        name: "Interior Deep Clean",
        description: "Extraction, steam sanitising and protection on every surface.",
        price: 260,
        duration: "6 – 10 h",
        featured: true,
        serviceSlug: "interior-detailing",
        includes: [
          "Hot-water extraction on carpets and fabric",
          "Steam sanitising of vents and switchgear",
          "Leather cleaned and conditioned",
          "Fabric and leather protection",
          "Headliner and boot",
        ],
      },
      {
        name: "Leather Protection",
        description: "Deep clean plus a breathable dye-transfer-resistant coating.",
        price: 190,
        duration: "4 h",
        serviceSlug: "leather-protection",
        includes: [
          "pH-appropriate deep clean",
          "Bolster and entry-point focus",
          "Breathable protective coating",
          "Steering wheel and door cards",
          "18-month warranty",
        ],
      },
    ],
  },
  {
    id: "protection",
    title: "Protection",
    description: "Ceramic coatings for paint, wheels and glass, applied over corrected surfaces.",
    options: [
      {
        name: "Coating — 3 Year",
        description: "Single-stage correction with a three-year silica coating.",
        price: 690,
        duration: "3 days",
        serviceSlug: "ceramic-coating",
        includes: [
          "Full decontamination",
          "Single-stage machine polish",
          "3-year coating on paint",
          "Glass and trim coated",
          "Aftercare kit",
        ],
      },
      {
        name: "Coating — 5 Year",
        description: "Two-stage correction with our most-requested coating system.",
        price: 1150,
        duration: "4 days",
        featured: true,
        serviceSlug: "ceramic-coating",
        includes: [
          "Two-stage machine polish",
          "Paint depth report",
          "5-year coating on paint",
          "Wheels, glass and exhaust tips coated",
          "Annual inspection included",
        ],
      },
      {
        name: "Coating — 10 Year",
        description: "Multi-stage correction and our flagship coating with annual servicing.",
        price: 1890,
        duration: "5 – 7 days",
        serviceSlug: "ceramic-coating",
        includes: [
          "Three-stage correction to target",
          "10-year coating system",
          "Wheels off, barrels coated",
          "Interior fabric and leather protection",
          "Two annual services included",
        ],
      },
      {
        name: "Wheel & Caliper Coating",
        description: "Wheels removed, barrels and calipers coated for high heat.",
        price: 220,
        duration: "1 day",
        serviceSlug: "wheel-protection",
        includes: [
          "All four wheels removed",
          "Faces and barrels decontaminated",
          "High-temperature ceramic",
          "Calipers coated",
          "2-year warranty",
        ],
      },
    ],
  },
  {
    id: "correction",
    title: "Paint Correction",
    description: "Measured defect removal. Every stage is quoted after paint depth readings.",
    options: [
      {
        name: "Enhancement — 1 Stage",
        description: "Removes light swirling and restores gloss on well-kept paint.",
        price: 450,
        duration: "1 day",
        serviceSlug: "paint-correction",
        includes: [
          "Full decontamination",
          "Paint depth readings",
          "Single polishing stage",
          "Panel wipe and inspection",
          "Six-month sealant",
        ],
      },
      {
        name: "Correction — 2 Stage",
        description: "Compounding and refining for the majority of defects.",
        price: 890,
        duration: "2 days",
        featured: true,
        serviceSlug: "paint-correction",
        includes: [
          "Compound and refine passes",
          "Trim masked, gaps taped",
          "Inspection under three light sources",
          "Written depth report",
          "12-month sealant",
        ],
      },
      {
        name: "Concours — 3 Stage",
        description: "Near-total defect removal on paint that can safely give it.",
        price: 1490,
        duration: "3 – 4 days",
        serviceSlug: "paint-correction",
        includes: [
          "Three correction stages",
          "Wet sanding where appropriate",
          "Jambs, shuts and hard-to-reach areas",
          "Full photographic record",
          "Coating strongly recommended",
        ],
      },
    ],
  },
  {
    id: "ppf",
    title: "Paint Protection Film",
    description:
      "Plotter-cut urethane film with wrapped edges. Coverage is confirmed on the car before booking.",
    options: [
      {
        name: "Front Impact Package",
        description: "Bumper, partial bonnet, fenders and mirrors.",
        price: 980,
        duration: "2 days",
        serviceSlug: "partial-ppf",
        includes: [
          "Front bumper and partial bonnet",
          "Front fenders",
          "Mirror caps",
          "Headlight units",
          "Edge sealing",
        ],
      },
      {
        name: "Track & Touring",
        description: "Full front end plus the panels that catch motorway debris.",
        price: 1600,
        duration: "3 days",
        featured: true,
        serviceSlug: "paint-protection-film",
        includes: [
          "Full bonnet and front fenders",
          "Front bumper and mirrors",
          "A-pillars and roof leading edge",
          "Door cups and sills",
          "Ceramic top coat over film",
        ],
      },
      {
        name: "Full Body",
        description: "Every painted panel, with disassembly for wrapped edges.",
        price: 3400,
        duration: "5 – 7 days",
        serviceSlug: "full-body-ppf",
        includes: [
          "All painted exterior panels",
          "Bumpers and lamps removed",
          "Multi-stage correction beforehand",
          "Ceramic coating over the film",
          "Photographic installation record",
        ],
      },
    ],
  },
  {
    id: "tinting",
    title: "Glass & Tinting",
    description: "Nano-ceramic film, plotter-cut and installed in a filtered bay.",
    options: [
      {
        name: "Rear Set",
        description: "Rear doors, quarter glass and rear screen.",
        price: 290,
        duration: "4 h",
        serviceSlug: "window-tinting",
        includes: [
          "Nano-ceramic film",
          "Plotter-cut patterns",
          "Heat-shrink formed rear screen",
          "99% UV rejection",
          "Lifetime film warranty",
        ],
      },
      {
        name: "Full Vehicle",
        description: "All side glass and rear screen at a legal shade.",
        price: 430,
        duration: "5 – 6 h",
        featured: true,
        serviceSlug: "window-tinting",
        includes: [
          "Every side window and rear screen",
          "Legal shade confirmed for your vehicle",
          "Infrared heat rejection",
          "No signal interference",
          "Lifetime film warranty",
        ],
      },
      {
        name: "Windscreen & Extras",
        description: "Clear IR windscreen film, sunroof or a top shade band.",
        price: 260,
        duration: "2 – 3 h",
        serviceSlug: "window-tinting",
        includes: [
          "Clear infrared windscreen film",
          "Sunroof film option",
          "Top shade band option",
          "Headlight protection film option",
          "Old film removal quoted separately",
        ],
      },
    ],
  },
];
